---
- name: Install Nano via RPM
  hosts: all
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Download the Nano RPM package
      ansible.builtin.get_url:
        url: https://rpmfind.net/linux/fedora/linux/development/rawhide/Everything/x86_64/os/Packages/n/nano-8.1-1.fc41.x86_64.rpm
        dest: /tmp/nano-8.1-1.fc41.x86_64.rpm

    - name: Install the Nano RPM package
      ansible.builtin.yum:
        name: /tmp/nano-8.1-1.fc41.x86_64.rpm
        state: present
        disable_gpg_check: yes

    - name: Clean up the downloaded RPM package
      ansible.builtin.file:
        path: /tmp/nano-8.1-1.fc41.x86_64.rpm
        state: absent
